---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  labels:
    type: proxy
    author: chaitanya
spec:
  replicas: 2 
  selector:
     matchLabels:
        type: proxy
  template:
     metadata: 
       name: nginx-pod
       labels: 
         type: proxy
     spec:
        containers:
          - name: mynginx
            image: nginx
            ports: 
              - containerPort: 80
                hostPort: 8080


...                  

