---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    author: chaitanya
spec:
  replicas: 2
  selector:
    matchLabels:
      author: chaitanya
  template:
    metadata:
      name: httpd-pod
      labels:
        author: chaitanya
    spec:
      containers:
        - name: myhttpd
          image: httpd
          resources:
            requests:
              memory: "64Mi"
              cpu: "250"
            limits:
              memory: "256Mi"
              cpu: "1000"
...
