---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: chaitanya
spec:
  containers:
    - name: mynginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: value
                operator: In
                values:
                  - chaitanya
...   
