---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    author: chaitanya
spec:
  replicas: 2
  selector:
    matchLabels:
      author: chaitanya
  template:
    metadata:
      name: http-pod
      labels:
        author: chaitanya
    spec:
      containers:
        - name: myhttpd
          image: httpd
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: value
                   operator: In
                   values:
                     - chaitanya
...
