---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    type: ci-cd
    author: chaitanya
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
   
        
  

...            

