---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels: 
    author: chaitanya
spec:  
  ports: 
    - targetPort: 5432
      port: 5432
  selector:
      type: db
      author: chaitanya


...        
