---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    author: chaitanya
    name: redisapp
spec:
  replicas: 1  
  selector: 
     matchLabels:
       name: redisapp
  template:
    metadata:
      name: redisapp-pod
      labels:
        name: redisapp
    spec: 
      containers: 
          - name: myredis-app
            image: redis  
...              
       

