---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-app
    author: chaitanya
spec:
  ports:
    - targetPort: 6380
      port: 6380
  selector:
     name: redisapp




...       

