---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    author: chaitanya
    name: resultapp
spec:
  replicas: 2
  selector:
     matchLabels:
       name: resultapp
  template: 
     metadata:
       name: result-app-pod
       labels:
          name: resultapp
     spec: 
       containers: 
         - name: myresultapp 
           image: dockersamples/examplevotingapp_result
...      

