---
apiVersion: v1
kind: Pod
metadata:
   name: httpd-ns
   namespace: test-ns
   labels:
      type: webserver
      author: chaitanya
spec: 
  containers:
    - name: myhttpd
      image: httpd
      ports: 
         - containerPort: 80
           hostPort: 8080


...             
