---
apiVersion: v1
kind: Pod
metadata:
  name: postgress-pod
  labels:
    type: db
    author: chaitanya
spec: 
  containers:
     - name: mydb
       image: postgres
       env: 
        - name: POSTGRES_PASSWORD
          value: chaitanya
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: charan 


...            
