---
apiVersion: v1
kind: ReplicationController
metadata:
    name: jenkins-rc
    labels:
       type: webserver
       author: chaitanya
spec: 
  replicas: 2
  template: 
     metadata: 
       name: jenkins-pod
       labels:
         type: webserver
     spec: 
       containers:
         - name: myjenkins
           image: jenkins/jenkins
           ports:
             - containerPort: 8080
               hostPort: 9090


                 
...         
