---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    type: webserver
    author: chaitanya
spec:
  replicas: 2
  template: 
     metadata:
       name: httpd-port
       labels:
         type: webserver
         author: chaitanya
     spec: 
       containers:
          - name: myhttpd
            image: httpd
            ports:
              - containerPort: 80
                hostPort: 0808


...                  


